$ANSIBLE_VAULT;1.1;AES256
38356437313232336233663966373934643238303463353036653862633032326338306262326362
3764663538316137646462666134366463396232623038610a653961613938316236326633613161
35333465373066636561303363343931306634363735343531663237373637326138626231396163
3332333331616538310a633963363665363662333931366663363030326234306230393235393135
30633563376265663634663537636165373237313962353266356136616434313334333231663164
3935636339303035343232393435353335333166373566313861